# Generated by Django 2.2 on 2022-12-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
                ('rollno', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=10)),
                ('phno', models.IntegerField()),
            ],
        ),
    ]
